query providers {
  providers {
    id
    tradingName
    phone
    addresses {
      id
      streetNumber
      streetName
      town
      city
      province
      areaCode
    }
    operatingTimes {
      id
      day
      opens
      closes
    }

    socials {
      id
      name
      username
    }
  }
}
